AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-game-server-manager

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    
Resources:
  DiscordPing:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: build/handlers
      Handler: discordPing.handler
      Events:
        DiscordPing:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
      - Statement:
        - Sid: SecretsManagerGetValuePolicy
          Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:GetResourcePolicy
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecretVersionIds
          Resource:
          - arn:aws:secretsmanager:us-west-2:758792894779:secret:/discord*


Outputs:
  DiscordPingEndpoint:
    Description: 'Endpoint for discord to ping with simple requests'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
