AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-game-server-manager

Parameters:
  GameServerInstance:
    Type: String
    Default: "none"
    Description: The instance ID of the server to be managed

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    
Resources:
  DiscordServerCommands:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: build/handlers
      Handler: discordServerCommands.handler
      Events:
        DiscordCommand:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
      - Statement:
        - Sid: SecretsManagerGetValuePolicy
          Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:GetResourcePolicy
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecretVersionIds
          Resource:
          - arn:aws:secretsmanager:us-west-2:758792894779:secret:/discord*
        - Sid: DescribeEC2Instance
          Effect: Allow
          Action:
          - ec2:DescribeInstances
          Resource:
          - "*"
        - Sid: StartStopInstance
          Effect: Allow
          Action:
          - ec2:StartInstances
          - ec2:StopInstances
          Resource:
          - Fn::Join:
            - ":"
            - - "arn"
              - !Ref AWS::Partition
              - "ec2"
              - !Ref AWS::Region
              - !Ref AWS::AccountId
              - !Sub "instance/${GameServerInstance}"
        
Outputs:
  DiscordCommandsEndpoint:
    Description: 'Endpoint for discord to hit with commands'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
